### PR TITLE
Replace deprecated streamlit api method

### LINKED ISSUE #273: Not working with current streamlit version
Due to changes in streamlit api, there is no longer attribute _is_running_with streamlit. 
image

### PR DESCRIPTION
**Pull request by Gizzio**
Fixes #273

### CODE REVIEW

**Review by danthe3rd — COMMENTED** [review]
Thanks a lot for the contribution! Do you think we can also be backward compatible with previous versions of streamlit?

**Comment by Gizzio** [comment]
I think it should be compatible, but I am not sure

**Comment by danthe3rd** [comment]
> I think it should be compatible, but I am not sure

Okay - happy to merge if you fix the tests/lint errors :)

**Comment by oddeirikigland** [comment]
Thank you for fixing this! @danthe3rd is it a planned release to pip soon? Or would it be possible to get a pre-release with this fix?

**Comment by danthe3rd** [comment]
Hum I would need to spend some time to fix the CI... I'll be quite busy in the coming months but I can try to do that if I get some bandwidth

**Comment by oddeirikigland** [comment]
Great, thank you!

**Pull request merged**
